easy_admin:
    entities:
        User:
            class: App\Entity\User
        Degree:
            class: App\Entity\Degree
        Type:
            class: App\Entity\Type
        Role:
            class: App\Entity\Role

